project:
  type: website
  output-dir: docs

website:
  title: "Site do Alex Baroni"
  navbar:
    left:
      - href: index.qmd
        text: Home
        text: Dashboard2
        href: dashboard2.qmd
      - about.qmd
        href: https://github.com/baronialex/dashboard2.git
        text: Github 


format:
  html:
    theme: lux
    css: styles.css
    toc: true



